version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  web:
    build: .
    command: bash start.sh
    volumes:
      - .:/usr/src/TestProject
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A TestProject worker -l info
    volumes:
      - .:/usr/src/TestProject
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  data: