version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
#      - POSTGRES_NAME=supportdb
      - POSTGRES_DB=supportdb
#      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789Cc

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/TestProject
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=supportdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789Cc
    depends_on:
      - db

