# Generated by Django 4.0 on 2022-01-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('firstapp', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unresolved', 'Нерешенная'), ('resolved', 'Решенная'), ('freezy', 'Замороженная')], default='unresolved', max_length=20)),
                ('messages', models.ManyToManyField(to='firstapp.Message', verbose_name='сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
