# Generated by Django 4.0 on 2021-12-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_cases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
