# Generated by Django 4.0 on 2021-12-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
