# Generated by Django 4.0.1 on 2022-01-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_tickets_messages_message_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
