# Generated by Django 4.0 on 2021-12-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_testcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
