# Generated by Django 4.0.1 on 2022-01-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
