# Generated by Django 4.0 on 2021-12-28 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_message',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='from_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
