# Generated by Django 4.0 on 2021-12-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_message_date_message_message_from_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user_id',
        ),
    ]
