# Generated by Django 4.0 on 2021-12-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_message_to_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_user_id',
            new_name='to_user_id',
        ),
    ]
