# Generated by Django 4.0 on 2022-01-05 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_rename_from_user_id_message_to_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tickets',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.message'),
            preserve_default=False,
        ),
    ]
