# Generated by Django 4.0 on 2022-01-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_rename_text_tickets_title_tickets_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='message',
        ),
    ]
