# Generated by Django 4.0 on 2022-01-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_tickets_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
