# Generated by Django 4.0 on 2022-01-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_rename_message_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='title',
        ),
    ]
