# Generated by Django 4.0 on 2022-01-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_remove_tickets_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='message',
        ),
        migrations.AddField(
            model_name='tickets',
            name='message',
            field=models.ManyToManyField(to='firstapp.Message', verbose_name='сообщения'),
        ),
    ]
