# Generated by Django 4.0 on 2022-01-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_alter_message_text_remove_tickets_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='message',
            new_name='messages',
        ),
    ]
